import "./globals.css";

import type { Metadata } from "next";

import Footer from "@/common/Footer";
import Header from "@/common/Header";

export const metadata: Metadata = {
  title: "CV Generator | jroyvibes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center items-center w-full text-center">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
